# PostgreSQL

#spring.datasource.url=jdbc:postgresql://localhost:5432/mpapp
spring.datasource.url=jdbc:postgresql://localhost:5432/mavepizon_app_team_lead
spring.datasource.username=postgres
spring.datasource.password=griffin@2006
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Maximum size allowed for a single file
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

cloudinary.cloud-name=dyrujho4x
cloudinary.api-key=551999558118743
cloudinary.api-secret=PTrsDIEwh9jSPfluekxKkqBQETk

server.port=8080