# PostgreSQL

spring.datasource.url=jdbc:postgresql://ep-long-brook-axobsy5y-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_uJSZyk9RhjT3
spring.datasource.driver-class-name=org.postgresql.Driver

# Required for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Maximum size allowed for a single file
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mavepizon@gmail.com
spring.mail.password=tvfpxyiycbzqdmsu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


cloudinary.cloud-name=dyrujho4x
cloudinary.api-key=551999558118743
cloudinary.api-secret=PTrsDIEwh9jSPfluekxKkqBQETk

server.port=8080

razorpay.key.id=rzp_test_TPwPnZnPYzysgK
razorpay.key.secret=2z3lAjMfzafNQ4eGcPXwpMyo

