# PostgreSQL

#spring.datasource.url=jdbc:postgresql://localhost:5432/mpapp
spring.datasource.url=jdbc:postgresql://localhost:5432/mavepizon_app_team_lead
spring.datasource.username=postgres
spring.datasource.password=griffin@2006
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Maximum size allowed for a single file
spring.servlet.multipart.max-file-size=10MB

# Maximum size allowed for a multipart request (total size)
spring.servlet.multipart.max-request-size=10MB

server.port=8080