-- Creates the OTP table before V1__production_hardening creates OTP indexes.
-- This is intentionally an early migration because V1 references this table.
CREATE TABLE IF NOT EXISTS otps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    otp_code VARCHAR(255),
    expiry_time TIMESTAMP,
    verification_attempts INTEGER NOT NULL DEFAULT 0,
    last_sent_at TIMESTAMP,
    verified_at TIMESTAMP,
    role VARCHAR(50)
);
